[package]
name = "fp"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2" # CSV parsing library
nalgebra = "0.31" # Matrix operations for regression
plotters = "0.3" # Visualization library
